"""add_user_embedding_api_profile

Revision ID: e23b22c205c4
Revises: fa1a139f2bc3
Create Date: 2025-11-26 15:54:01.454910

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23b22c205c4'
down_revision = 'fa1a139f2bc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('embedding_api_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'api_profiles', ['embedding_api_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'embedding_api_profile_id')
    # ### end Alembic commands ###
