"""Add background column to Persona table

Revision ID: fa1a139f2bc3
Revises: 308fdebd9337
Create Date: 2025-11-26 11:25:43.407357

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1a139f2bc3'
down_revision = '308fdebd9337'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('background', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'background')
    # ### end Alembic commands ###
